platform :ios,'8.0'
use_frameworks!

target 'LiangCangZangChunyu' do
pod "SnapKit"
pod "SDWebImage"
pod "JSONModel"
pod "MJRefresh"
pod "FMDB"
pod "MBProgressHUD"

 # 主模块(必须)
pod 'ShareSDK3'
 # Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
pod 'MOBFoundation'

 # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'

 # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
 # pod 'ShareSDK3/ShareSDKPlatforms/QQ'
 # pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

 # pod 'ShareSDK3/ShareSDKPlatforms/RenRen'
 # pod 'ShareSDK3/ShareSDKPlatforms/AliPaySocial'
 # pod 'ShareSDK3/ShareSDKPlatforms/Kakao'

pod 'AMap3DMap'  #3D地图SDK
pod 'AMapSearch' #搜索服务SDK
pod 'AMapNavi'  #导航SDK
pod 'AMapLocation'  #定位SDK
end
